import { LaunchRegion } from '../domain/Region';

export const LAUNCH_REGIONS: LaunchRegion[] = [
  {
    slug: 'india',
    name: 'India',
    type: 'country',
    status: 'research',
    priority: 'P0',
    scope: {
      country: 'India',
      providerCodes: ['WBBUS', 'WBTC', 'BMTC_OFFICIAL', 'KSRTC_KARNATAKA', 'KERALA_RTC', 'DELHI_OTD'],
    },
    providers: [
      {
        code: 'WBBUS',
        name: 'WBBus',
        modes: ['BUS'],
        status: 'beta',
        adapterKey: 'wbbus',
      },
      {
        code: 'DELHI_OTD',
        name: 'Delhi Open Transit Data',
        modes: ['BUS', 'METRO'],
        status: 'research',
        adapterKey: 'delhi-otd',
      },
    ],
    supportedApis: ['stops', 'routes', 'journey-planned', 'coverage'],
    notes: 'National shell for global APIs and cross-state planning.',
  },
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    type: 'state',
    status: 'beta',
    priority: 'P0',
    scope: {
      country: 'India',
      state: 'West Bengal',
      providerCodes: ['WBBUS', 'WBTC', 'NBSTC', 'SBSTC'],
    },
    providers: [
      {
        code: 'WBBUS',
        name: 'WBBus',
        modes: ['BUS'],
        status: 'beta',
        adapterKey: 'wbbus',
        notes: 'Current implementation focus.',
      },
      {
        code: 'WBTC',
        name: 'West Bengal Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'wbtc',
      },
      {
        code: 'NBSTC',
        name: 'North Bengal State Transport Corporation',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'nbstc',
      },
      {
        code: 'SBSTC',
        name: 'South Bengal State Transport Corporation',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'sbstc',
      },
    ],
    supportedApis: ['stops', 'routes', 'journey-planned', 'coverage'],
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    type: 'state',
    status: 'research',
    priority: 'P1',
    scope: {
      country: 'India',
      state: 'Kerala',
      providerCodes: ['KERALA_RTC', 'KOCHI_METRO', 'KOCHI_WATER_METRO'],
    },
    providers: [
      {
        code: 'KERALA_RTC',
        name: 'Kerala State Road Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'kerala-rtc',
      },
      {
        code: 'KOCHI_METRO',
        name: 'Kochi Metro',
        modes: ['METRO'],
        status: 'research',
        adapterKey: 'kochi-metro',
      },
      {
        code: 'KOCHI_WATER_METRO',
        name: 'Kochi Water Metro',
        modes: ['FERRY'],
        status: 'research',
        adapterKey: 'kochi-water-metro',
      },
    ],
    supportedApis: ['stops', 'routes', 'journey-planned', 'coverage'],
  },
  {
    slug: 'bengaluru',
    name: 'Bengaluru',
    type: 'city',
    status: 'research',
    priority: 'P0',
    scope: {
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      providerCodes: ['BMTC_OFFICIAL', 'BMTC_FACILITIES', 'BMRCL'],
    },
    providers: [
      {
        code: 'BMTC_OFFICIAL',
        name: 'Bengaluru Metropolitan Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'bmtc',
      },
      {
        code: 'BMRCL',
        name: 'Namma Metro',
        modes: ['METRO'],
        status: 'research',
        adapterKey: 'bmrcl',
      },
    ],
    supportedApis: ['stops', 'routes', 'journey-planned', 'coverage'],
    notes: 'City launch region inside Karnataka; use this for Bengaluru-specific API rollout.',
  },
  {
    slug: 'karnataka',
    name: 'Karnataka',
    type: 'state',
    status: 'research',
    priority: 'P1',
    scope: {
      country: 'India',
      state: 'Karnataka',
      providerCodes: ['BMTC_OFFICIAL', 'KSRTC_KARNATAKA', 'NWKRTC', 'KKRTC', 'BMRCL'],
    },
    providers: [
      {
        code: 'KSRTC_KARNATAKA',
        name: 'Karnataka State Road Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'ksrtc-karnataka',
      },
      {
        code: 'BMTC_OFFICIAL',
        name: 'Bengaluru Metropolitan Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'bmtc',
      },
      {
        code: 'NWKRTC',
        name: 'North Western Karnataka Road Transport Corporation',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'nwkrtc',
      },
      {
        code: 'KKRTC',
        name: 'Kalyana Karnataka Road Transport Corporation',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'kkrtc',
      },
    ],
    supportedApis: ['stops', 'routes', 'journey-planned', 'coverage'],
  },
  {
    slug: 'global',
    name: 'Global',
    type: 'global',
    status: 'planned',
    priority: 'P3',
    scope: {
      providerCodes: [],
    },
    providers: [],
    supportedApis: ['coverage'],
    notes: 'Reserved for non-India expansion; provider drivers should still implement the same contracts.',
  },
];
