import { LaunchRegion } from '../domain/Region';

export const LAUNCH_REGIONS: LaunchRegion[] = [
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    type: 'state',
    status: 'beta',
    priority: 'P0',
    scope: {
      country: 'India',
      state: 'West Bengal',
      providerCodes: [
        'WBBUS',
        'WBTC',
        'SBSTC',
        'NBSTC',
        'KOLKATA_METRO',
        'EASTERN_RAILWAY_SUBURBAN',
        'WB_FERRY',
        'KOLKATA_AUTO',
        'KOLKATA_TRAM',
      ],
    },
    providers: [
      {
        code: 'WBBUS',
        name: 'WBBus',
        modes: ['BUS'],
        status: 'beta',
        adapterKey: 'wbbus',
        notes: 'Implemented adapter; next action is live import stabilization at 25, 100, then full dataset scale.',
      },
      {
        code: 'WBTC',
        name: 'West Bengal Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'wbtc',
        notes: 'Next West Bengal government bus adapter after WBBus stabilization.',
      },
      {
        code: 'SBSTC',
        name: 'South Bengal State Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'sbstc',
      },
      {
        code: 'NBSTC',
        name: 'North Bengal State Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'nbstc',
      },
      {
        code: 'KOLKATA_METRO',
        name: 'Metro Railway Kolkata',
        modes: ['METRO'],
        status: 'research',
        adapterKey: 'kolkata-metro',
      },
      {
        code: 'EASTERN_RAILWAY_SUBURBAN',
        name: 'Eastern Railway suburban services',
        modes: ['SUBURBAN_RAIL'],
        status: 'research',
        adapterKey: 'eastern-railway-suburban',
      },
      {
        code: 'WB_FERRY',
        name: 'West Bengal ferry services',
        modes: ['FERRY'],
        status: 'research',
        adapterKey: 'wb-ferry',
      },
      {
        code: 'KOLKATA_AUTO',
        name: 'Kolkata auto route notifications',
        modes: ['SHARED_AUTO'],
        status: 'planned',
        adapterKey: 'kolkata-auto',
        notes: 'Notification data proves route publication, not current daily operation.',
      },
      {
        code: 'KOLKATA_TRAM',
        name: 'Kolkata tram services',
        modes: ['TRAM'],
        status: 'planned',
        adapterKey: 'kolkata-tram',
        notes: 'Preserve active, suspended, and historical status separately.',
      },
    ],
    supportedApis: ['bus-routes', 'bus-stops', 'provider-runs', 'dataset-versions', 'coverage'],
    notes:
      'Launch objective: strongest statewide private + government + metro + rail + ferry mobility coverage. Core areas must reach walking-enabled journey planning before public launch.',
  },
  {
    slug: 'bengaluru',
    name: 'Bengaluru',
    type: 'city',
    status: 'beta',
    priority: 'P0',
    scope: {
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      providerCodes: [
        'BMRCL_METRO',
        'BMTC_OFFICIAL',
        'KSRTC_KARNATAKA',
        'OSM_ROAD_NETWORK_BENGALURU',
        'BENGALURU_AUTO',
        'BENGALURU_SHUTTLE',
      ],
    },
    providers: [
      {
        code: 'BMRCL_METRO',
        name: 'Namma Metro / BMRCL',
        modes: ['METRO'],
        status: 'beta',
        adapterKey: 'bmrcl',
        notes: 'Implemented adapter; next action is live import stabilization.',
      },
      {
        code: 'BMTC_OFFICIAL',
        name: 'Bengaluru Metropolitan Transport Corporation',
        modes: ['BUS'],
        status: 'research',
        adapterKey: 'bmtc-official',
        notes:
          'Regular, express, limited-stop, airport, metro-feeder, night, and premium services stay under BMTC_OFFICIAL using serviceClass.',
      },
      {
        code: 'KSRTC_KARNATAKA',
        name: 'KSRTC Karnataka Bengaluru connections',
        modes: ['INTERCITY_BUS'],
        status: 'planned',
        adapterKey: 'ksrtc-karnataka',
      },
      {
        code: 'OSM_ROAD_NETWORK_BENGALURU',
        name: 'OpenStreetMap road and pedestrian network',
        modes: ['WALKING', 'CYCLING', 'ROAD'],
        status: 'planned',
        adapterKey: 'osm-road-network-bengaluru',
        notes: 'Routing graph source, not a timetable provider.',
      },
      {
        code: 'BENGALURU_AUTO',
        name: 'Bengaluru auto observations',
        modes: ['AUTO'],
        status: 'planned',
        adapterKey: 'bengaluru-auto',
      },
      {
        code: 'BENGALURU_SHUTTLE',
        name: 'Bengaluru shuttle observations',
        modes: ['SHUTTLE'],
        status: 'planned',
        adapterKey: 'bengaluru-shuttle',
      },
    ],
    supportedApis: ['metro-lines', 'metro-stations', 'bus-routes', 'bus-stops', 'provider-runs', 'dataset-versions', 'coverage'],
    notes:
      'Launch objective: complete city-level BMTC + Metro + airport + walking journey planning before broader Karnataka rollout.',
  },
  {
    slug: 'karnataka',
    name: 'Karnataka',
    type: 'state',
    status: 'research',
    priority: 'P1',
    scope: {
      country: 'India',
      state: 'Karnataka',
      providerCodes: ['KSRTC_KARNATAKA', 'NWKRTC', 'KKRTC', 'MYSURU_URBAN', 'HUBBALLI_DHARWAD', 'MANGALURU_PRIVATE_BUS'],
    },
    providers: [
      {
        code: 'KSRTC_KARNATAKA',
        name: 'Karnataka State Road Transport Corporation',
        modes: ['INTERCITY_BUS'],
        status: 'planned',
        adapterKey: 'ksrtc-karnataka',
      },
      {
        code: 'NWKRTC',
        name: 'North Western Karnataka Road Transport Corporation',
        modes: ['INTERCITY_BUS'],
        status: 'planned',
        adapterKey: 'nwkrtc',
      },
      {
        code: 'KKRTC',
        name: 'Kalyana Karnataka Road Transport Corporation',
        modes: ['INTERCITY_BUS'],
        status: 'planned',
        adapterKey: 'kkrtc',
      },
      {
        code: 'MYSURU_URBAN',
        name: 'Mysuru urban services',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'mysuru-urban',
      },
      {
        code: 'HUBBALLI_DHARWAD',
        name: 'Hubballi-Dharwad services',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'hubballi-dharwad',
      },
      {
        code: 'MANGALURU_PRIVATE_BUS',
        name: 'Mangaluru private buses',
        modes: ['BUS'],
        status: 'planned',
        adapterKey: 'mangaluru-private-bus',
      },
    ],
    supportedApis: ['provider-runs', 'dataset-versions', 'coverage'],
    notes:
      'Karnataka statewide providers remain inside scope, but must not delay the Bengaluru public launch.',
  },
];
