import { ProviderRegistryEntry } from '../../domain/mobility-provider.interface';

export const BENGALURU_PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  {
    code: 'BMTC_OFFICIAL',
    adapterKey: 'bmtc-official-provider',
    name: 'BMTC Official Portal',
    sourceType: 'GOVERNMENT',
    website: 'https://mybmtc.karnataka.gov.in/english',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'Official HTML pages and PDFs',
    status: 'ACTIVE_DEVELOPMENT',
    sourceUrls: [
      'https://mybmtc.karnataka.gov.in/english',
      'https://mybmtc.karnataka.gov.in/33/bus-stations/en',
      'https://mybmtc.karnataka.gov.in/new-page/Metro%20Feeder%20Route%20details/en',
      'https://mybmtc.karnataka.gov.in/info-3/Daily%2BWeekly%2BMonthly%2BPasses/en',
      'https://mybmtc.karnataka.gov.in/70/%E0%B2%AA%E0%B2%A4%E0%B3%8D%E0%B2%B0%E0%B2%BF%E0%B2%95%E0%B2%BE-%E0%B2%AA%E0%B3%8D%E0%B2%B0%E0%B2%95%E0%B2%9F%E0%B2%A3%E0%B3%86/en',
    ],
    notes: [
      'Authoritative parent source for BMTC city, suburban, feeder, facility, pass, and notice data.',
      'Parse facilities separately from route stops.',
      'Metro feeder routes are serviceClass = METRO_FEEDER under BMTC_OFFICIAL, not a separate provider identity.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceAlert',
    ],
  },
  {
    code: 'NAMMA_BMTC_AVLS',
    adapterKey: 'namma-bmtc-avls-provider',
    name: 'Namma BMTC AVLS',
    sourceType: 'GOVERNMENT_APP',
    website: 'https://nammabmtcapp.karnataka.gov.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'Journey planning and realtime app; access review required',
    status: 'RESEARCH_REQUIRES_ACCESS_REVIEW',
    sourceUrls: ['https://nammabmtcapp.karnataka.gov.in/'],
    notes: [
      'Do not bypass authentication, tokens, CAPTCHA, rate limits, or technical restrictions.',
      'Mark as research only until public-data terms are confirmed.',
    ],
    canonicalTargets: [
      'providers',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'RealtimeVehiclePosition',
    ],
  },
  {
    code: 'BMTC_GTFS_REFERENCE',
    adapterKey: 'generic-gtfs-provider',
    name: 'BMTC GTFS reference datasets',
    sourceType: 'THIRD_PARTY',
    website: 'https://github.com/Vonter/bmtc-gtfs',
    version: 'v1',
    priority: 'P2',
    modes: ['BUS'],
    access: 'Unofficial GTFS references and fixtures',
    status: 'RESEARCH_ONLY',
    sourceUrls: [
      'https://github.com/Vonter/bmtc-gtfs',
      'https://hub.tumidata.org/dataset/gtfs-bengaluru',
    ],
    notes: [
      'Use only as fixtures/research until publisher, license, freshness, and permissions are verified.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
    ],
  },
  {
    code: 'BMRCL',
    adapterKey: 'bmrcl-metro-provider',
    name: 'Namma Metro / BMRCL',
    sourceType: 'GOVERNMENT',
    website: 'https://www.bmrc.co.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['METRO'],
    access: 'Official HTML timings, ticket, fare, and network pages',
    status: 'ACTIVE_DEVELOPMENT',
    sourceUrls: [
      'https://www.bmrc.co.in/',
      'https://www.bmrc.co.in/metro-timings/',
      'https://www.bmrc.co.in/tickets/',
      'https://www.bmrc.co.in/fare-rules/',
    ],
    notes: [
      'Do not store planned or under-construction lines as active services.',
      'Every metro record should include operational status and effective dates where available.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceCalendar',
      'Interchange',
      'ServiceAlert',
    ],
  },
  {
    code: 'BMTC_AIRPORT',
    adapterKey: 'bmtc-airport-provider',
    name: 'BMTC Vayu Vajra airport buses',
    sourceType: 'GOVERNMENT',
    website: 'https://mybmtc.karnataka.gov.in/english',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS'],
    access: 'BMTC official portal and schedule PDFs',
    status: 'RESEARCH',
    sourceUrls: ['https://mybmtc.karnataka.gov.in/storage/pdf-files/VajraForm3Eng.pdf'],
    notes: [
      'Model as BMTC serviceFamily = VAYU_VAJRA.',
      'Third-party airport timing pages are discovery/comparison only.',
    ],
    canonicalTargets: ['routePatterns', 'trips', 'fares', 'frequencies', 'observations', 'AirportTerminal'],
  },
  {
    code: 'BMTC_FACILITIES',
    adapterKey: 'bmtc-facilities-provider',
    name: 'BMTC stations, TTMCs, and depots',
    sourceType: 'GOVERNMENT',
    website: 'https://mybmtc.karnataka.gov.in/33/bus-stations/en',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS'],
    access: 'Official station directory',
    status: 'ACTIVE_DEVELOPMENT',
    sourceUrls: ['https://mybmtc.karnataka.gov.in/33/bus-stations/en'],
    notes: [
      'Create facility records first.',
      'Do not treat every station address as a route stop automatically.',
    ],
    canonicalTargets: ['nodes', 'observations', 'Facility'],
  },
  {
    code: 'DULT_TRANSITGIS',
    adapterKey: 'dult-transitgis-provider',
    name: 'DULT TransitGIS',
    sourceType: 'GOVERNMENT_GIS',
    website: 'https://dult.karnataka.gov.in/138/transit-gis/en',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS', 'METRO', 'WALKING', 'CYCLING'],
    access: 'GIS portal investigation',
    status: 'RESEARCH_REQUIRED',
    sourceUrls: ['https://dult.karnataka.gov.in/138/transit-gis/en'],
    notes: [
      'Determine documented APIs/downloads/license/currentness.',
      'Do not scrape map tiles as route data.',
    ],
    canonicalTargets: ['nodes', 'routePatterns', 'observations', 'GeospatialLayer'],
  },
  {
    code: 'KSRTC_KARNATAKA',
    adapterKey: 'ksrtc-karnataka-provider',
    name: 'KSRTC Karnataka',
    sourceType: 'GOVERNMENT',
    website: 'https://ksrtc.karnataka.gov.in/english',
    version: 'v1',
    priority: 'P1',
    modes: ['INTERCITY_BUS'],
    access: 'Official site and reservation/search investigation',
    status: 'PLANNED',
    sourceUrls: ['https://ksrtc.karnataka.gov.in/english'],
    notes: ['Keep BMTC and KSRTC as separate agencies even when they share terminals.'],
    canonicalTargets: ['agencies', 'nodes', 'routePatterns', 'trips', 'fares', 'observations'],
  },
  {
    code: 'KRIDE_SUBURBAN_RAIL',
    adapterKey: 'kride-suburban-rail-provider',
    name: 'Bengaluru suburban rail',
    sourceType: 'GOVERNMENT',
    website: 'https://kride.in/',
    version: 'v1',
    priority: 'P2',
    modes: ['SUBURBAN_RAIL'],
    access: 'Project/status source investigation',
    status: 'RESEARCH_REQUIRED',
    sourceUrls: ['https://kride.in/'],
    notes: ['Do not generate passenger journeys until service is confirmed operational.'],
    canonicalTargets: ['nodes', 'routePatterns', 'observations', 'ProjectPhase'],
  },
  {
    code: 'INDIAN_RAILWAYS_BENGALURU',
    adapterKey: 'indian-railways-bengaluru-provider',
    name: 'Indian Railways Bengaluru stations',
    sourceType: 'GOVERNMENT',
    website: 'https://indianrailways.gov.in/',
    version: 'v1',
    priority: 'P2',
    modes: ['SUBURBAN_RAIL'],
    access: 'Station identity source investigation',
    status: 'RESEARCH',
    sourceUrls: ['https://indianrailways.gov.in/'],
    notes: ['Initial scope: stations, aliases, coordinates, and interchanges only.'],
    canonicalTargets: ['nodes', 'observations', 'Interchange'],
  },
  {
    code: 'BENGALURU_COMMUNITY_MOBILITY',
    adapterKey: 'bengaluru-community-mobility-provider',
    name: 'Bengaluru community mobility observations',
    sourceType: 'COMMUNITY',
    website: 'https://yatroo.local/community',
    version: 'v1',
    priority: 'P3',
    modes: ['AUTO', 'SHUTTLE'],
    access: 'Moderated community submissions',
    status: 'PLANNED',
    sourceUrls: [],
    notes: ['Do not invent fixed auto routes where normal autos operate point-to-point.'],
    canonicalTargets: ['nodes', 'routePatterns', 'frequencies', 'fares', 'observations', 'CommunityVerification'],
  },
  {
    code: 'OSM_BENGALURU',
    adapterKey: 'osm-bengaluru-network-provider',
    name: 'OpenStreetMap Bengaluru Network',
    sourceType: 'OPEN_DATA',
    website: 'https://www.openstreetmap.org/',
    version: 'v1',
    priority: 'P0',
    modes: ['WALKING', 'CYCLING', 'ROAD'],
    access: 'Routing engine import, not tile scraping',
    status: 'PLANNED',
    sourceUrls: ['https://www.openstreetmap.org/'],
    notes: [
      'Use Valhalla, GraphHopper, or OSRM for routing.',
      'Do not insert walking paths as ordinary transit routes.',
    ],
    canonicalTargets: ['observations', 'RoutingGraph'],
  },
];

export const BENGALURU_PROVIDER_PRIORITY = [
  'BMTC_OFFICIAL',
  'BMRCL',
  'BMTC_FACILITIES',
  'BMTC_AIRPORT',
  'OSM_BENGALURU',
  'NAMMA_BMTC_AVLS',
  'KSRTC_KARNATAKA',
  'KRIDE_SUBURBAN_RAIL',
  'BENGALURU_COMMUNITY_MOBILITY',
  'BMTC_GTFS_REFERENCE',
  'DULT_TRANSITGIS',
  'INDIAN_RAILWAYS_BENGALURU',
];
