import { ProviderRegistryEntry } from '../../domain/mobility-provider.interface';

export const BENGALURU_PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  {
    code: 'BMRCL_METRO',
    adapterKey: 'bmrcl-metro-provider',
    name: 'Namma Metro / BMRCL',
    sourceType: 'GOVERNMENT',
    website: 'https://www.bmrc.co.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['METRO'],
    access: 'Official HTML network, timing, fare, and alert pages',
    status: 'ACTIVE_DEVELOPMENT',
    sourceUrls: [
      'https://www.bmrc.co.in/',
      'https://www.bmrc.co.in/metro-network/',
      'https://www.bmrc.co.in/metro-timings/',
      'https://www.bmrc.co.in/fare-rules/',
    ],
    notes: [
      'Implemented first end-to-end adapter; next step is live import stabilization.',
      'Add first/last train, operating hours, fares, and alerts after lines/stations are stable.',
      'Preserve effective dates because network and operating information can change.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceCalendar',
      'Interchange',
      'ServiceAlert',
    ],
  },
  {
    code: 'BMTC_OFFICIAL',
    adapterKey: 'bmtc-official-provider',
    name: 'Bengaluru Metropolitan Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://mybmtc.karnataka.gov.in/english',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'Official HTML route pages, timetable pages, notices, and PDFs',
    status: 'ACTIVE_DEVELOPMENT',
    sourceUrls: [
      'https://mybmtc.karnataka.gov.in/english',
      'https://mybmtc.karnataka.gov.in/33/bus-stations/en',
      'https://mybmtc.karnataka.gov.in/new-page/Metro%20Feeder%20Route%20details/en',
      'https://mybmtc.karnataka.gov.in/storage/pdf-files/VajraForm3Eng.pdf',
      'https://mybmtc.karnataka.gov.in/info-3/Daily%2BWeekly%2BMonthly%2BPasses/en',
    ],
    notes: [
      'Use serviceClass for REGULAR, EXPRESS, LIMITED_STOP, AIRPORT, METRO_FEEDER, NIGHT, and PREMIUM.',
      'Metro feeder remains providerCode = BMTC_OFFICIAL, mode = BUS, serviceClass = METRO_FEEDER.',
      'Vayu Vajra and premium services remain under BMTC_OFFICIAL unless a separate data owner/lifecycle is proven.',
      'Facilities, TTMCs, depots, and bus stops must be resolved separately.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceCalendar',
      'ServiceAlert',
      'Facility',
      'AirportTerminal',
    ],
  },
  {
    code: 'KSRTC_KARNATAKA',
    adapterKey: 'ksrtc-karnataka-provider',
    name: 'KSRTC Karnataka',
    sourceType: 'GOVERNMENT',
    website: 'https://ksrtc.in/',
    version: 'v1',
    priority: 'P1',
    modes: ['INTERCITY_BUS'],
    access: 'Official site and permission-aware reservation/search investigation',
    status: 'PLANNED',
    sourceUrls: ['https://ksrtc.in/'],
    notes: [
      'Initial scope is Bengaluru connections after BMTC/BMRCL are stable.',
      'Do not bypass authentication, CAPTCHA, anti-bot controls, or protected booking APIs.',
      'Separate operator identity from service classification.',
    ],
    canonicalTargets: ['agencies', 'nodes', 'routePatterns', 'trips', 'fares', 'observations'],
  },
  {
    code: 'OSM_ROAD_NETWORK_BENGALURU',
    adapterKey: 'osm-road-network-bengaluru-provider',
    name: 'OpenStreetMap Bengaluru road and pedestrian network',
    sourceType: 'OPEN_DATA',
    website: 'https://www.openstreetmap.org/',
    version: 'v1',
    priority: 'P1',
    modes: ['WALKING', 'CYCLING', 'ROAD'],
    access: 'Approved routing/data pipeline; not tile scraping',
    status: 'PLANNED',
    sourceUrls: ['https://www.openstreetmap.org/'],
    notes: [
      'Use for walking first/last mile, walking transfers, station entrances, and cycling where permitted.',
      'Do not treat the road network as a normal timetable provider.',
      'Use OSRM, GraphHopper, Valhalla, or another approved routing graph pipeline.',
    ],
    canonicalTargets: ['observations', 'RoutingGraph', 'TransferEdge', 'StationEntrance'],
  },
  {
    code: 'BENGALURU_AUTO',
    adapterKey: 'bengaluru-auto-provider',
    name: 'Bengaluru auto observations',
    sourceType: 'COMMUNITY',
    website: 'https://yatroo.local/community',
    version: 'v1',
    priority: 'P2',
    modes: ['AUTO'],
    access: 'Moderated community/operator contributions until official sources are found',
    status: 'PLANNED',
    sourceUrls: [],
    notes: [
      'Do not invent route, fare, or frequency data.',
      'Autos are normally point-to-point; fixed-route claims need current official/operator/community verification.',
    ],
    canonicalTargets: ['nodes', 'routePatterns', 'fares', 'observations', 'CommunityVerification'],
  },
  {
    code: 'BENGALURU_SHUTTLE',
    adapterKey: 'bengaluru-shuttle-provider',
    name: 'Bengaluru shuttle observations',
    sourceType: 'COMMUNITY',
    website: 'https://yatroo.local/community',
    version: 'v1',
    priority: 'P2',
    modes: ['SHUTTLE'],
    access: 'Moderated community/operator contributions until official sources are found',
    status: 'PLANNED',
    sourceUrls: [],
    notes: ['Do not publish route, fare, or frequency data without current official, operator, or verified community observations.'],
    canonicalTargets: ['nodes', 'routePatterns', 'trips', 'fares', 'observations', 'CommunityVerification'],
  },
];

export const BENGALURU_PROVIDER_PRIORITY = [
  'BMRCL_METRO',
  'BMTC_OFFICIAL',
  'KSRTC_KARNATAKA',
  'OSM_ROAD_NETWORK_BENGALURU',
  'BENGALURU_AUTO',
  'BENGALURU_SHUTTLE',
];
