import { ProviderRegistryEntry } from '../../domain/mobility-provider.interface';

export const WEST_BENGAL_PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  {
    code: 'WBBUS',
    adapterKey: 'wbbus-provider',
    name: 'WBBus',
    sourceType: 'COMMUNITY',
    website: 'https://wbbus.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML + pagination',
    status: 'RESEARCH',
    sourceUrls: ['https://wbbus.in/', 'https://wbbus.in/allbus'],
    notes: [
      'Main private and mixed bus source.',
      'Treat as community/private data, not official truth.',
      'Preserve source page, scrape date, confidence, and warnings.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'observations',
      'Vehicle',
    ],
  },
  {
    code: 'WBTC_ROUTES',
    adapterKey: 'wbtc-routes-provider',
    name: 'WBTC city bus routes',
    sourceType: 'GOVERNMENT',
    website: 'https://wbtconline.in/wbtc-city-bus-routes',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML table',
    status: 'RESEARCH',
    sourceUrls: ['https://wbtconline.in/wbtc-city-bus-routes'],
    notes: [
      'Best suited for route patterns, not complete scheduled trips.',
      'Current operation should be validated separately.',
    ],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'observations'],
  },
  {
    code: 'WB_TRANSPORT_REGISTRY',
    adapterKey: 'wb-transport-registry-provider',
    name: 'West Bengal Transport Department registry',
    sourceType: 'GOVERNMENT',
    website: 'https://transport.wb.gov.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS', 'TRAM', 'FERRY'],
    access: 'HTML sitemap and department pages',
    status: 'RESEARCH',
    sourceUrls: [
      'https://transport.wb.gov.in/',
      'https://transport.wb.gov.in/transport-services/bus-services/',
      'https://transport.wb.gov.in/sitemap/',
    ],
    notes: ['Use as a discovery/provider-registry source, not one giant scraper.'],
    canonicalTargets: ['providers', 'observations'],
  },
  {
    code: 'SBSTC',
    adapterKey: 'sbstc-provider',
    name: 'South Bengal State Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://sbstc.co.in/',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS'],
    access: 'Public site plus reservation search investigation',
    status: 'RESEARCH',
    sourceUrls: ['https://sbstc.co.in/', 'https://sbstconline.co.in/reservation-home'],
    notes: [
      'Do not bypass authentication, CAPTCHA, or anti-bot controls.',
      'Log as BLOCKED_REQUIRES_PERMISSION if automated access is unclear.',
    ],
    canonicalTargets: ['providers', 'agencies', 'routePatterns', 'trips', 'fares', 'observations'],
  },
  {
    code: 'NBSTC',
    adapterKey: 'nbstc-provider',
    name: 'North Bengal State Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://nbstc.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML route pages',
    status: 'RESEARCH',
    sourceUrls: ['https://nbstc.in/', 'https://nbstc.in/bus-routes.php'],
    notes: ['P0 for North Bengal route and service discovery.'],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'trips', 'observations'],
  },
  {
    code: 'KOLKATA_METRO',
    adapterKey: 'kolkata-metro-provider',
    name: 'Metro Railway Kolkata',
    sourceType: 'GOVERNMENT',
    website: 'https://mtp.indianrailways.gov.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['METRO'],
    access: 'Official HTML timetable, fare chart, and service updates',
    status: 'RESEARCH',
    sourceUrls: [
      'https://mtp.indianrailways.gov.in/',
      'https://mtp.indianrailways.gov.in/view_section.jsp?backgroundColor=LIGHTSTEELBLUE&fontColor=black&id=0%2C2%2C630&lang=0',
      'https://mtp.indianrailways.gov.in/view_section.jsp?id=0%2C2%2C661&lang=0',
      'https://mtp.indianrailways.gov.in/view_section.jsp?id=0%2C4%2C268&lang=0',
    ],
    notes: [
      'Do not hard-code only Blue and Green lines.',
      'Version timetables and alerts by effective date.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceCalendar',
      'ServiceAlert',
      'Interchange',
    ],
  },
  {
    code: 'WB_FERRY',
    adapterKey: 'wb-ferry-provider',
    name: 'West Bengal ferry services',
    sourceType: 'GOVERNMENT',
    website: 'https://transport.wb.gov.in/transport-services/ferry-services/ferry-routes/',
    version: 'v1',
    priority: 'P1',
    modes: ['FERRY'],
    access: 'Official HTML route directory and notices',
    status: 'RESEARCH',
    sourceUrls: [
      'https://transport.wb.gov.in/transport-services/ferry-services/ferry-routes/',
      'https://transport.wb.gov.in/transport-services/ferry-services/passenger-ferry-services/',
    ],
    notes: ['Old notices should not automatically be treated as current timings.'],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'trips', 'frequencies', 'fares', 'observations'],
  },
  {
    code: 'KOLKATA_TRAM',
    adapterKey: 'kolkata-tram-provider',
    name: 'Kolkata tram services',
    sourceType: 'GOVERNMENT',
    website: 'https://transport.wb.gov.in/transport-services/tram-route/',
    version: 'v1',
    priority: 'P3',
    modes: ['TRAM'],
    access: 'Official historical/reference HTML plus notifications',
    status: 'RESEARCH',
    sourceUrls: ['https://transport.wb.gov.in/transport-services/tram-route/'],
    notes: [
      'Treat as historical/reference until active status is verified.',
      'Every route must carry operationalStatus.',
    ],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'frequencies', 'observations'],
  },
  {
    code: 'KOLKATA_AUTO_NOTIFICATIONS',
    adapterKey: 'kolkata-auto-notifications-provider',
    name: 'Kolkata auto-rickshaw route notifications',
    sourceType: 'GOVERNMENT',
    website: 'https://transport.wb.gov.in/',
    version: 'v1',
    priority: 'P2',
    modes: ['SHARED_AUTO'],
    access: 'PDF notifications and RTA proceedings',
    status: 'RESEARCH',
    sourceUrls: [
      'https://transport.wb.gov.in/wp-content/uploads/2017/04/2017-03-31-notification-on-auto-routes-n-maximum-permits-in-Kolkata-1276.pdf',
      'https://transport.wb.gov.in/wp-content/uploads/2023/03/1111-WT_21-03-2023.pdf',
      'https://transport.wb.gov.in/wp-content/uploads/2023/08/RTA_-03-03-2023.pdf',
    ],
    notes: [
      'Notifications prove route notification/amendment, not current frequency or fare.',
      'Requires operator/community verification for daily operation.',
    ],
    canonicalTargets: ['providers', 'nodes', 'routePatterns', 'observations', 'PermitLimit'],
  },
  {
    code: 'EASTERN_RAILWAY_SUBURBAN',
    adapterKey: 'eastern-railway-suburban-provider',
    name: 'Eastern Railway suburban services',
    sourceType: 'GOVERNMENT',
    website: 'https://er.indianrailways.gov.in/',
    version: 'v1',
    priority: 'P2',
    modes: ['SUBURBAN_RAIL'],
    access: 'Official train search, notices, and topology PDFs',
    status: 'RESEARCH',
    sourceUrls: [
      'https://er.indianrailways.gov.in/',
      'https://er.indianrailways.gov.in/view_section.jsp?backgroundColor=LIGHTSTEELBLUE&fontColor=black&id=0%2C2%2C422%2C424&lang=0',
    ],
    notes: ['Use older PDFs for topology discovery only, not current operations.'],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'trips', 'observations', 'ServiceCalendar'],
  },
];

export const WEST_BENGAL_PROVIDER_PRIORITY = [
  'WBBUS',
  'WBTC_ROUTES',
  'NBSTC',
  'KOLKATA_METRO',
  'SBSTC',
  'WB_FERRY',
  'EASTERN_RAILWAY_SUBURBAN',
  'KOLKATA_AUTO_NOTIFICATIONS',
  'KOLKATA_TRAM',
];

