import { ProviderRegistryEntry } from '../../domain/mobility-provider.interface';

export const WEST_BENGAL_PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  {
    code: 'WBBUS',
    adapterKey: 'wbbus-provider',
    name: 'WBBus.in Transport Directory',
    sourceType: 'COMMUNITY',
    website: 'https://wbbus.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML + pagination',
    status: 'ACTIVE',
    sourceUrls: ['https://wbbus.in/', 'https://wbbus.in/allbus'],
    notes: [
      'Main private and mixed bus source.',
      'Scrapes bus routes, stops, bus names, route numbers, intermediate stops, operator information.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'observations',
    ],
  },
  {
    code: 'WBBUSTIME',
    adapterKey: 'wbbustime-provider',
    name: 'WBBustime Timetable & Stop Network',
    sourceType: 'COMMUNITY',
    website: 'https://wbbustime.com/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML DOM & JSON APIs',
    status: 'ACTIVE',
    sourceUrls: ['https://wbbustime.com/'],
    notes: [
      'Provides route search, stop search, stop lists, timetables, bus info, recently updated routes, rural stop coverage.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'frequencies',
      'observations',
    ],
  },
  {
    code: 'BUSSATHI',
    adapterKey: 'bussathi-provider',
    name: 'Bus Sathi Transit Network',
    sourceType: 'COMMUNITY',
    website: 'https://bussathi.in/',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS'],
    access: 'HTML DOM & REST API',
    status: 'ACTIVE',
    sourceUrls: ['https://bussathi.in/'],
    notes: [
      'Bus search, route search, stop search, government/private buses, timetable info, route validation.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
    ],
  },
  {
    code: 'OPENSTREETMAP',
    adapterKey: 'openstreetmap-provider',
    name: 'OpenStreetMap Global Spatial Network',
    sourceType: 'OPEN_DATA',
    website: 'https://www.openstreetmap.org/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS', 'METRO', 'SUBURBAN_RAIL', 'TRAM', 'FERRY', 'WALKING', 'ROAD'],
    access: 'Overpass API JSON',
    status: 'ACTIVE',
    sourceUrls: ['https://www.openstreetmap.org/'],
    notes: [
      'Villages, roads, bus stops, railway stations, ferry terminals, metro stations, tram stops, coordinates, administrative boundaries.',
    ],
    canonicalTargets: ['providers', 'nodes', 'observations'],
  },
  {
    code: 'NOMINATIM',
    adapterKey: 'nominatim-provider',
    name: 'Nominatim Geocoding & Village Resolution',
    sourceType: 'OPEN_DATA',
    website: 'https://nominatim.openstreetmap.org/',
    version: 'v1',
    priority: 'P0',
    modes: ['ROAD', 'BUS', 'WALKING'],
    access: 'REST JSON API',
    status: 'ACTIVE',
    sourceUrls: ['https://nominatim.openstreetmap.org/', 'https://nominatim.org/'],
    notes: [
      'Village search, reverse geocoding, coordinates, place resolution.',
    ],
    canonicalTargets: ['providers', 'nodes', 'observations'],
  },
  {
    code: 'CENSUS_INDIA',
    adapterKey: 'census-india-provider',
    name: 'Census of India Administrative Directory',
    sourceType: 'GOVERNMENT',
    website: 'https://censusindia.gov.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['ROAD'],
    access: 'CSV / Excel Administrative Datasets',
    status: 'ACTIVE',
    sourceUrls: ['https://censusindia.gov.in/'],
    notes: [
      'Village directory, district, block, Gram Panchayat, population.',
    ],
    canonicalTargets: ['providers', 'nodes', 'observations'],
  },
  {
    code: 'DATA_GOV_INDIA',
    adapterKey: 'data-gov-india-provider',
    name: 'Open Government Data India (data.gov.in)',
    sourceType: 'OPEN_DATA',
    website: 'https://data.gov.in/',
    version: 'v1',
    priority: 'P1',
    modes: ['BUS', 'METRO', 'SUBURBAN_RAIL', 'FERRY', 'ROAD'],
    access: 'REST JSON / CSV Datasets',
    status: 'ACTIVE',
    sourceUrls: ['https://data.gov.in/'],
    notes: [
      'GIS datasets, administrative datasets, transport datasets, public infrastructure.',
    ],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'observations'],
  },
  {
    code: 'WBTC',
    adapterKey: 'wbtc-provider',
    name: 'West Bengal Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://wbtconline.in/wbtc-city-bus-routes',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML table',
    status: 'RESEARCH',
    sourceUrls: [
      'https://wbtconline.in/wbtc-city-bus-routes',
      'https://transport.wb.gov.in/transport-services/bus-services/',
    ],
    notes: [
      'Best suited for route patterns, not complete scheduled trips.',
      'Current operation should be validated separately.',
    ],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'observations'],
  },
  {
    code: 'SBSTC',
    adapterKey: 'sbstc-provider',
    name: 'South Bengal State Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://sbstc.co.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'Public site plus reservation search investigation',
    status: 'RESEARCH',
    sourceUrls: ['https://sbstc.co.in/', 'https://sbstconline.co.in/reservation-home'],
    notes: [
      'Do not bypass authentication, CAPTCHA, or anti-bot controls.',
      'Log as BLOCKED_REQUIRES_PERMISSION if automated access is unclear.',
    ],
    canonicalTargets: ['providers', 'agencies', 'routePatterns', 'trips', 'fares', 'observations'],
  },
  {
    code: 'NBSTC',
    adapterKey: 'nbstc-provider',
    name: 'North Bengal State Transport Corporation',
    sourceType: 'GOVERNMENT',
    website: 'https://nbstc.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['BUS'],
    access: 'HTML route pages',
    status: 'RESEARCH',
    sourceUrls: ['https://nbstc.in/', 'https://nbstc.in/bus-routes.php'],
    notes: ['P0 for North Bengal route and service discovery.'],
    canonicalTargets: ['providers', 'agencies', 'nodes', 'routePatterns', 'trips', 'observations'],
  },
  {
    code: 'KOLKATA_METRO',
    adapterKey: 'kolkata-metro-provider',
    name: 'Metro Railway Kolkata',
    sourceType: 'GOVERNMENT',
    website: 'https://mtp.indianrailways.gov.in/',
    version: 'v1',
    priority: 'P0',
    modes: ['METRO'],
    access: 'Official HTML timetable, fare chart, and service updates',
    status: 'RESEARCH',
    sourceUrls: [
      'https://mtp.indianrailways.gov.in/',
      'https://mtp.indianrailways.gov.in/view_section.jsp?backgroundColor=LIGHTSTEELBLUE&fontColor=black&id=0%2C2%2C630&lang=0',
    ],
    notes: [
      'Do not hard-code only Blue and Green lines.',
      'Version timetables and alerts by effective date.',
    ],
    canonicalTargets: [
      'providers',
      'agencies',
      'nodes',
      'routePatterns',
      'trips',
      'fares',
      'observations',
      'ServiceCalendar',
      'ServiceAlert',
      'Interchange',
    ],
  },
];

export const WEST_BENGAL_PROVIDER_PRIORITY = [
  'WBBUS',
  'WBBUSTIME',
  'BUSSATHI',
  'OPENSTREETMAP',
  'NOMINATIM',
  'CENSUS_INDIA',
  'DATA_GOV_INDIA',
  'WBTC',
  'NBSTC',
  'SBSTC',
  'KOLKATA_METRO',
];
